<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

 <parent>
        <groupId>com.veadan.folib</groupId>
        <artifactId>folib-parent</artifactId>
        <version>3.0-SNAPSHOT</version>
        <relativePath/>
    </parent>

    <artifactId>folib-security</artifactId>
    <packaging>pom</packaging>
    <name>Folib: Security</name>
    <inceptionYear>2019</inceptionYear>

     <scm>
        <url>http://git.folib.com/folib/folib-server</url>
        <connection>scm:git:git://git.folib.com/folib/folib-server.git</connection>
        <developerConnection>scm:git:git://git.folib.com/folib/folib-server.git</developerConnection>
    </scm>
    <licenses>
        <license>
             <name>Mulan Public License, Version 2</name>
             <url>https://license.coscl.org.cn/MulanPubL-2.0</url>
            <distribution>repo</distribution>
            <comments>Mulan PubL v2 is a copyleft license with terms on code disclosure and attribution. Approved by OSI.</comments>
        </license>
    </licenses>
    <modules>
        <module>folib-authentication-api</module>
        <module>folib-authentication-providers</module>
        <module>folib-authentication-registry</module>
        <module>folib-authentication-support</module>
        <module>folib-security-api</module>
        <module>folib-user-management</module>
    </modules>

</project>
