const typeList = [
    {
        src:'images/folib/raw.svg',
        type:'raw',
        name:'Raw'
    },
    {
        src:'images/folib/maven.svg',
        type:'maven',
        name:'Maven'
    },
    {
        src:'images/folib/npm.svg',
        type:'npm',
        name:'Npm'
    },
    {
        src:'images/folib/yarn.svg',
        type:'yarn',
        name:'Yarn'
    },
    {
        src:'images/folib/nuget.svg',
        type:'nuget',
        name:'NuGet'
    },
    {
        src:'images/folib/ivy.svg',
        type:'ivy',
        name:'Ivy'
    },
    {
        src:'images/folib/sbt.svg',
        type:'sbt',
        name:'SBT'
    },
    {
        src:'images/folib/gradle.svg',
        type:'gradle',
        name:'Gradle'
    },
    {
        src:'images/folib/rpm.svg',
        type:'rpm',
        name:'Rpm'
    },
    {
        src:'images/folib/docker.svg',
        type:'docker',
        name:'Docker'
    },
    {
        src:'images/folib/php.svg',
        type:'php',
        name:'Php'
    },
    {
        src:'images/folib/pypi.svg',
        type:'pypi',
        name:'PyPi'
    },
    {
        src:'images/folib/conan.svg',
        type:'conan',
        name:'Conan'
    },
    {
        src:'images/folib/helm.svg',
        type:'helm',
        name:'Helm'
    },
    {
        src:'images/folib/cocoapods.svg',
        type:'cocoapods',
        name:'CocoaPods'
    },
    {
        src:'images/folib/go.svg',
        type:'go',
        name:'Go'
    },
    {
        src:'images/folib/ohpm.svg',
        type:'ohpm',
        name:'Ohpm'
    },
    {
        src:'images/folib/gitlfs.svg',
        type:'gitlfs',
        name:'Git LFS'
    },
    {
        src:'images/folib/huggingface.svg',
        type:'huggingface',
        name:'huggingface'
    },
    {
        src:'images/folib/pub.svg',
        type:'pub',
        name:'Pub'
    },
    {
        src:'images/folib/debian.svg',
        type:'debian',
        name:'Debian'
    },
]

export default typeList