map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

upstream websocket {
    server localhost:9527;
}
server {
        listen 9527;
        server_name localhost;
        root /dist;
        index index.html;
        try_files $uri $uri/ /index.html;
         location /api/ {
               proxy_pass http://192.168.5.8:38080/api/;
               client_max_body_size    2000m;
            }
         location /scanner/ {
               proxy_pass http://192.168.5.8:38081/scanner/;
               client_max_body_size    2000m;
            }
         location /storages/ {
                       proxy_pass http://192.168.5.8:38080/storages/;
                       client_max_body_size    2000m;
                    }
         location /v2/ {
                       proxy_pass http://192.168.5.8:38080/v2/;
                       client_max_body_size    2000m;
                    }

}

