name: Maven build
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: euleros-2.10.1
    steps:
    - uses: checkout-action@0.0.1
    - name: Set up JDK
      uses: setup-java@0.0.1
      run: cd repo_workspace && java  -version
      with:
        java-version: '17.0.2'

