#!/bin/bash
echo "=====>>>>> 创建并授权 ~/folib/es/"
mkdir -p ~/folib/es/data && mkdir -p ~/folib/es/plugins && mkdir -p ~/folib/es/conf
chmod 777 ~/folib/es/*

echo "=====>>>>> 创建并授权 ~/folib/mirror"
mkdir -p ~/folib/mirror
chmod 777 ~/folib/mirror

echo "=====>>>>> 修改文件句柄数至655360"
echo vm.max_map_count=655360 >> /etc/sysctl.conf
sysctl -p /etc/sysctl.conf