DROP TABLE IF EXISTS `storage_monitoring`;

CREATE TABLE `storage_monitoring` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `storage_id` varchar(255) DEFAULT '' COMMENT '存储空间名称',
  `storage_provider` varchar(255) DEFAULT 'local' COMMENT '文件存储方式',
  `repository_id` varchar(255) DEFAULT '' COMMENT '仓库名称',
  `repository_type` varchar(255) DEFAULT '' COMMENT '仓库类型',
  `repository_layout` varchar(255) DEFAULT '' COMMENT '仓库布局',
  `repository_sub_layout` varchar(255) DEFAULT '' COMMENT '仓库子布局',
  `storage_path` varchar(1000) DEFAULT '' COMMENT '存储路径',
  `artifacts_size` decimal(32,2) DEFAULT '0.00' COMMENT '制品大小',
  `artifacts_count` bigint(20) DEFAULT '0' COMMENT '制品数量',
  `files_size` decimal(32,2) DEFAULT '0.00' COMMENT '文件大小',
  `files_count` bigint(20) DEFAULT '0' COMMENT '文件数量',
  `used_files_size_percentage` decimal(32,2) DEFAULT '0.00' COMMENT '文件使用存储占比',
  `folders_count` bigint(20) DEFAULT '0' COMMENT '文件夹数量',
  `items_count` bigint(20) DEFAULT '0' COMMENT '条目数量',
  `storage_quota_size` decimal(32,2) DEFAULT '0.00' COMMENT '存储空间配额大小',
  `used_storage_quota_size_percentage` decimal(32,2) DEFAULT '0.00' COMMENT '已使用存储空间配额大小占比',
  `other_files_size` decimal(32,2) DEFAULT '0.00' COMMENT '其他文件大小',
  `used_other_files_size_percentage` decimal(32,2) DEFAULT '0.00' COMMENT '其他文件使用存储占比',
  `storage_count` int(11) DEFAULT '0' COMMENT '存储空间数量',
  `repository_count` int(11) DEFAULT '0' COMMENT '仓库数量',
  `artifacts_downloaded_count` bigint(20) DEFAULT '0' COMMENT '制品下载量',
  `storage_device_name` varchar(255) DEFAULT '' COMMENT '存储设备名称',
  `storage_device_type` varchar(255) DEFAULT 'NAS' COMMENT '存储设备类型',
  `storage_device_size` decimal(32,2) DEFAULT '0.00' COMMENT '存储设备总容量',
  `storage_device_usable_size` decimal(32,2) DEFAULT '0.00' COMMENT '存储设备可用大小',
  `used_storage_device_size` decimal(32,2) DEFAULT '0.00' COMMENT '存储设备已使用大小',
  `used_storage_device_size_percentage` decimal(32,2) DEFAULT '0.00' COMMENT '已使用存储设备大小占比',
  `data_type` int(3) DEFAULT '1' COMMENT '数据类型 1 仓库 2 回收站 3 存储空间 4 平台 5 存储设备',
  `is_latest` tinyint(3) DEFAULT '1' COMMENT '是否是最新数据 1 是 0 否',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_storage_id` (`storage_id`) USING BTREE,
  KEY `idx_repository_id` (`repository_id`) USING BTREE,
  KEY `idx_repository_type` (`repository_type`) USING BTREE,
  KEY `idx_repository_layout` (`repository_layout`) USING BTREE,
  KEY `idx_repository_sub_layout` (`repository_sub_layout`) USING BTREE,
  KEY `idx_data_type` (`data_type`) USING BTREE,
  KEY `idx_storage_provider` (`storage_provider`) USING BTREE,
  KEY `idx_storage_device_name` (`storage_device_name`) USING BTREE,
  KEY `idx_storage_device_type` (`storage_device_type`) USING BTREE,
  KEY `idx_is_latest` (`is_latest`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='存储监控';