DROP TABLE IF EXISTS `webhook_events_log`;

CREATE TABLE `webhook_events_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `event_type` varchar(255) COLLATE utf8mb4_bin DEFAULT '' COMMENT '事件类型',
  `event_repository_id` varchar(255) COLLATE utf8mb4_bin DEFAULT '' COMMENT '事件仓库名称',
  `storage_id` varchar(255) COLLATE utf8mb4_bin DEFAULT '' COMMENT '存储空间名称',
  `repository_id` varchar(255) COLLATE utf8mb4_bin DEFAULT '' COMMENT '仓库名称',
  `artifact_name` varchar(255) COLLATE utf8mb4_bin DEFAULT '' COMMENT '制品名称',
  `artifact_path` varchar(1000) COLLATE utf8mb4_bin DEFAULT '' COMMENT '制品路径',
  `sha256_checksum` varchar(255) COLLATE utf8mb4_bin DEFAULT '' COMMENT 'sha256的checksum',
  `size` bigint(20) DEFAULT 0 COMMENT '文件大小',
  `base_url` varchar(255) COLLATE utf8mb4_bin DEFAULT '' COMMENT '访问url前缀',
  `status` int(11) DEFAULT 1 COMMENT '状态 （1：初始状态 2：成功 3：失败）',
  `failure_reason` text COMMENT '失败的原因',
  `retry` int(11) DEFAULT 1 COMMENT '是否重试（0:不重试，1:重试）',
  `retry_count` int(11) DEFAULT 0 COMMENT '重试次数',
  `retry_time` datetime DEFAULT NULL COMMENT '重试时间',
  `create_by` varchar(255) DEFAULT '' COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(255) DEFAULT '' COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_storage_id` (`storage_id`) USING BTREE,
  KEY `idx_repository_id` (`repository_id`) USING BTREE,
  KEY `idx_artifact_name` (`artifact_name`) USING BTREE,
  KEY `idx_event_type` (`event_type`) USING BTREE,
  KEY `idx_event_repository_id` (`event_repository_id`) USING BTREE,
  KEY `idx_status` (`status`) USING BTREE,
  KEY `idx_retry` (`retry`) USING BTREE,
  KEY `idx_retry_count` (`retry_count`) USING BTREE,
  KEY `idx_sha256_checksum` (`sha256_checksum`) USING BTREE,
  KEY `idx_create_time` (`create_time`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='webhook事件记录';
