server:
  port: 38080
  connection-timeout: 50000
  session:
      timeout: 50000
  jetty:
    acceptor: 32 # Number of acceptor threads to use.
    max-http-post-size: 524288000 # Maximum size in bytes of the HTTP post or put content.
    selectors: 64 # Number of selector threads to use.
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${folib.mysql.host:10.10.33.145}:${folib.mysql.port:3306}/${folib.mysql.db:folib_scanner}?useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF8
    username: ${folib.mysql.user:root}
    password: ${folib.mysql.password:199088926}

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  liquibase:
    enabled: false
  servlet:
    multipart:
      enabled: true

mybatis:
  mapper-locations: "classpath*:mapper/*.xml"

mapper:
  mappers: com.veadan.folib.scanner.common.base.CommonMapper
  identity: MYSQL

scan:
  base-proxy: ${folib.nvd:110.40.184.113:9998/}    #扫描网络代理地址
  storage-base: ${folib.vault}/
  thread-pool: 200

folib:
  basedir: .
  home: ${folib.basedir}/folib
  vault: ${folib.basedir}/folib-vault
  etc: ${folib.home}/etc
  temp: ${folib.home}/tmp
  config:
    file: ${folib.home}/etc/conf/folib.yaml
  storage:
    booter:
      basedir: ${folib.vault}/storages
  host: localhost
  port: 38080
  nuget:
    download:
      feed: false
  version: @{project.version}
  revision: @{folib.revision}
  users:
    external:
      cache:
        seconds: 3600
  sse:
    timeoutMillis: 600000
  graph:
    gremlin:
        server:
            enabled: true
# Changes to these properties must also be applied to [folib/folib-web-integration-tests] and possibly the pipeline.
# Please ping us on our chat channel (https://chat.carlspring.org/) to confirm.
logging:
  debug: false
  console:
    enabled: true
  file:
    name: ${logging.dir}/folib.log
    enabled: true
    size:
      single: 128MB
      total: 1GB
    history: 31
  dir: ${folib.vault}/logs
java:
  io:
    tmpdir: ${folib.vault}/tmp
ehcache:
  disk:
    store:
      dir: ${folib.vault}/cache
management:
  health:
    neo4j:
      enabled: false
    ldap:
      enabled: false
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,beans,metrics,trace,scheduledtasks,threaddump,loggers,startup
      base-path: /api/monitoring
cacheManagerConfiguration:
  groupConfig:
    name: folib
    password: password
  enableMulticastConfig: false
  multicast:
    multicastGroup: 224.2.2.3
    multicastPort: 54327
    multicastTimeoutSeconds: 2
    multicastTimeToLive: 32
    trustedInterfaces: en0,en1
    loopbackModeEnabled: false
  instanceId: folib
  caches:
    remoteRepositoryAliveness:
      maxSizeLimit: 1000
      maxSizePolicy: FREE_HEAP_SIZE
      evictionPolicy: LFU
    tags:
      maxSizeLimit: 1000
      maxSizePolicy: FREE_HEAP_SIZE
      evictionPolicy: LFU
    authentications:
      cacheLocalEntries: true
      evictionConfigSize: 1000
      evictionConfigMaxSizePolicy: ENTRY_COUNT
      invalidateOnChange: true
      timeToLiveSeconds: 10
