server:
  port: 38080
  connection-timeout: 50000
  session:
      timeout: 50000
  jetty:
    max-http-form-post-size: 524288000 # Maximum size in bytes of the HTTP post or put content.

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${folib.mysql.host:127.0.0.1}:${folib.mysql.port:3306}/${folib.mysql.db:folib_scanner}?createDatabaseIfNotExist=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF8
    username: ${folib.mysql.user:root}
    password: ${folib.mysql.password:123456}
    schema: classpath:db/sql/database-init.sql
  liquibase:
      change-log: classpath:db/changelog-master.xml

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
  # redis 配置
  redis:
    enabled: ${folib.redis.enabled:false}
#    # 地址
#    host: ${folib.redis.host:192.168.5.8}
#    # 端口，默认为6379
#    port: ${folib.redis.port:6379}
#    # 数据库索引
#    database: 0
#    # 密码
#    password: ${folib.redis.password:123456}
#    # 连接超时时间
#    timeout: 10s
#    lettuce:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池的最大数据库连接数
#        max-active: 8
#        # #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
    cluster:
      nodeAddresses: ${folib.redis.host:redis://127.0.0.1:6379}
    #      nodeAddresses: ${folib.redis.host:redis://192.168.5.100:7000,redis://192.168.5.100:7001,redis://192.168.5.100:7002,redis://192.168.5.100:7003,redis://192.168.5.100:7004,redis://192.168.5.100:7005}
    password: ${folib.redis.password:123456}
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper:
  mappers: com.veadan.folib.scanner.common.base.CommonMapper
  identity: MYSQL

scan:
  base-proxy: ${folib.nvd:nvd.folib.com}    #扫描网络代理地址
  storage-base: ${folib.vault}/
  thread-pool: 200

folib:
  basedir: .
  home: ${folib.basedir}/folib
  vault: ${folib.basedir}/folib-vault
  etc: ${folib.home}/etc
  temp: ${folib.vault}/tmp
  multipart:
    maxFileSize: 2048             # 单个上传文件大小 （MB）
    maxRequestSize: 2048        # 单次个上传文件总大小 （MB）
  cluster:
    openflag: ${folib.openflag:true}
  docker:
    getAppPackagePathConfig: usr/local/app # docker 扫描提供获取指定路径下的应用包 多个路径逗号隔开
  distributed:
    lockip: ${folib.scheduled.lockip:10.8.10.166} # 实例 host ip
  config:
    file: ${folib.home}/etc/conf/folib.yaml
  storage:
    booter:
      basedir: ${folib.vault}/storages
  host: localhost
  port: 38080
  dependentLibraryPrefix: anhui
  dependentPushUrl: http://172.29.63.45:9022
  nuget:
    download:
      feed: false
  version: @{project.version}
  revision: @{folib.revision}
  users:
    external:
      cache:
        seconds: 3600
  sse:
    timeoutMillis: 600000
  graph:
    gremlin:
        server:
            enabled: true
  threadPool:
    async:
      corePoolSize: 12
      maxPoolSize: 12
      queueCapacity: 2147483647
      keepAliveSeconds: 0
      threadNamePrefix: async_
      awaitTerminationSeconds: 60
    asyncEventListener:
      corePoolSize: 12
      maxPoolSize: 12
      queueCapacity: 2147483647
      keepAliveSeconds: 0
      threadNamePrefix: asyncEventListener_
      awaitTerminationSeconds: 0
    asyncConfig:
      corePoolSize: 2
      maxPoolSize: 2
      queueCapacity: 2147483647
      keepAliveSeconds: 0
      threadNamePrefix: asyncConfig_
      awaitTerminationSeconds: 60
    asyncFetchRemotePackage:
      corePoolSize: 12
      maxPoolSize: 12
      queueCapacity: 2147483647
      keepAliveSeconds: 0
      threadNamePrefix: asyncFetchRemotePackage_
      awaitTerminationSeconds: 0
    asyncScan:
      corePoolSize: 16
      maxPoolSize: 16
      queueCapacity: 2147483647
      keepAliveSeconds: 0
      threadNamePrefix: asyncScan_
      awaitTerminationSeconds: 0
# Changes to these properties must also be applied to [folib/folib-web-integration-tests] and possibly the pipeline.
# Please ping us on our chat channel (https://chat.carlspring.org/) to confirm.
logging:
  debug: false
  console:
    enabled: true
  file:
    name: ${logging.dir}/folib.log
    enabled: true
    size:
      single: 128MB
      total: 1GB
    history: 31
  dir: ${folib.vault}/logs
java:
  io:
    tmpdir: ${folib.vault}/tmp
ehcache:
  disk:
    store:
      dir: ${folib.vault}/cache
management:
  health:
    neo4j:
      enabled: false
    ldap:
      enabled: false
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,beans,metrics,trace,scheduledtasks,threaddump,loggers,startup
      base-path: /api/monitoring
cacheManagerConfiguration:
  groupConfig:
    name: folib
    password: password
  enableMulticastConfig: false
  multicast:
    multicastGroup: 224.2.2.3
    multicastPort: 54327
    multicastTimeoutSeconds: 2
    multicastTimeToLive: 32
    trustedInterfaces: en0,en1
    loopbackModeEnabled: false
  instanceId: folib
  caches:
    remoteRepositoryAliveness:
      maxSizeLimit: 1000
      maxSizePolicy: FREE_HEAP_SIZE
      evictionPolicy: LFU
    tags:
      maxSizeLimit: 1000
      maxSizePolicy: FREE_HEAP_SIZE
      evictionPolicy: LFU
    authentications:
      cacheLocalEntries: true
      evictionConfigSize: 1000
      evictionConfigMaxSizePolicy: ENTRY_COUNT
      invalidateOnChange: true
      timeToLiveSeconds: 10


s3fs:
  path:
    style:
      access: true
  connection:
    timeout: 50
  max:
    connections: 1000
  protocol: http
#  region: sh1a
  region: folib
#  uri: s3://s3.sh1a.qingstor.com
  uri: s3://192.168.5.100:9000
  access:
#    key: HRKZYMEFVAJMZMMUXBNG
    key: admin
  secret:
#    key: KjIm1Cl3V9TBK0HQmlH3j3KYEM83FmILv5AIJwAg
    key: admin@V587
rsa:
  privateKey: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAIyu/3z87O6l94pIricIgo1VpYvNuK/StdlehIaQM6R9PmDAr5/phnFYWJEh+ZhMUIl6c/qIvcQr0y0Q2FRPF6085l4QLvbJI+FQ9xSspKWFGEzUuoEVogOtjlBz0Fl3VXO0wmZSrCnUhF14PWWBNz5e0X1ZIVEreGWj4XrCR+NjAgMBAAECgYB53Kig2vJdstQfK9/3Hc8AoHzbAiOF4e710ILZkRW62WZsJty6l22GxzFI3nY3L3vf6nuGPGatBA1UDzBkr3Jgqm0TSKSqlZokmCs3v1/gtkr/TSt36F58lAswR4I5iPdcDXkNfViidzqnvCahpwWpUAjteeUsx1hBQM1p8gWvOQJBANFs78S/EXfmkxy0d4Pf7uoFRXlrMC4SpP/9AjKHaRexbLesG4jYXLclx16pZXj7VqOWBORcVBKn9y1guFOnYdUCQQCr+G3EsX++e8G32lYmYnNp082Fg+tGSz2RG/LrwDqJOSyuB87LFJcRphNdo266f23SpQI2luqh91ByiBatPRRXAkBNlZTyB3LaP4JqlPTd1xz0d4V4aNxNhTy5VSr2OzIUw/cpyEnfFYCrnQRSLmFYQ4yiR9aCHy5KRw2MMxO2cgENAkAs9RRVQIYB2T6qftTY0hIUD4ACMJuYU+Ezh1f5U9a5uw24LWhdZPOddIpJh4lSDjA6ylKKzOdoEkygtH0hKv+fAkBcHH9QUQsUE40ffNcITptbMJGfQzkl3yYCwuM8xrK3KyvYLSk5qL+xcCnTloboTjVNuwgJWuiujBy6DlAZTAj/
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCMrv98/OzupfeKSK4nCIKNVaWLzbiv0rXZXoSGkDOkfT5gwK+f6YZxWFiRIfmYTFCJenP6iL3EK9MtENhUTxetPOZeEC72ySPhUPcUrKSlhRhM1LqBFaIDrY5Qc9BZd1VztMJmUqwp1IRdeD1lgTc+XtF9WSFRK3hlo+F6wkfjYwIDAQAB
